spring.application.name=smartcampus-backend
server.port=9090
spring.mongodb.uri=mongodb+srv://smart_campus:Yuvanu123456@cluster0.exbnej2.mongodb.net/smart_campus?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.uri=mongodb+srv://smart_campus:Yuvanu123456@cluster0.exbnej2.mongodb.net/smart_campus?retryWrites=true&w=majority&appName=Cluster0