spring.application.name=smartcampus-backend
server.port=9090

spring.data.mongodb.uri=mongodb+srv://campusadmin:xTJ6UmUOiXQYbJ9j@cluster0.mfna91h.mongodb.net/smartcampus?retryWrites=true&w=majority&appName=Cluster0

spring.datasource.url=jdbc:h2:mem:smartcampus
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=email,profile