spring.application.name=smartcampus-backend
server.port=9090
# Set this env var before running: MONGODB_PASSWORD
spring.mongodb.uri=mongodb+srv://yuvanujan:${MONGODB_PASSWORD}@cluster0.7gww6tj.mongodb.net/smart_campus?retryWrites=true&w=majority&appName=Cluster0